### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by Dylan95** [praeclarum/Csg#1]
I think you're forgetting something here.  

You wrote in the readme: "This library is a manual port of OpenJsCad's csg.js".  that library has the MIT licence, but I didn't find a copy of it anywhere in your project.  Porting software to another language is a kind of modification, so you've got to include that licence file.

**Comment by praeclarum** [comment]
This is MIT licensed too.

**Comment by Dylan95** [comment]
I see, but that's just for this library.  I'm think you've got to include the original as well.  I know you gave credit to the original author in the README, but technically that's not enough.  I would do something like copying https://github.com/jscad/csg.js/blob/master/LICENSE to a new file: licenses/jscad_LICENSE.  Licenses can sure be a pain right?

**Comment by praeclarum** [comment]
Oh sure. I was thinking because they were both MIT it was ok. But you’re right, the copyrights are different.

**Comment by praeclarum** [comment]
Added!
